### ISSUE TITLE
The more training steps, the worse the result

### ISSUE THREAD

**Issue by yftongbupt** [timothybrooks/instruct-pix2pix#102]
I use instruct pix2pix to train a style transfer model, my dataset has about 8,000 image pairs and the instruction is just "change the style to ……". I found that the more steps the model trains, the worse the inference result to get and the result changes to irrelevant to the original image. Such as I want to change a photo to anime style, but I get a twisted figure.
Does anyone have similar question or know why?

**Comment by lsabrinax** [comment]
I have the same  problem

**Comment by crisz94** [comment]
@yftongbupt @lsabrinax hey guys, I have a similiar problem as well.. Did you guys find any clues about this question?

**Comment by caojiehui** [comment]
I have the same problem...

**Comment by mo230761** [comment]
Did you guys find any clues about this question?
