### ISSUE TITLE
Automatic1111 integration

### ISSUE THREAD

**Issue by guzuligo** [timothybrooks/instruct-pix2pix#11]
Is it possible to use this with the automatic1111 webui?

I tried downloading the ckpt and used the config file, but it seems it is not enough.

**Comment by holynski** [comment]
Sorry, we haven't integrated into that framework. We do, however, have our own web UI that you can use by calling `python edit_app.py`. We'll also soon have a HuggingFace demo.

If you end up integrating into that UI, feel free to submit a pull request with any relevant changes.
