### ISSUE TITLE
Cannot Download Checkpoint

### ISSUE THREAD

**Issue by ziqipang** [timothybrooks/instruct-pix2pix#119]
Hi, Thanks for the nice work!

I am trying to download the pretrained checkpoint using the `download_checkpoint.sh`. However, it seems the link is no longer valid. It would help a lot if any new links are available or the models could be shared via other ways (e.g. huggingface, etc.).

Thank you!

![image](https://github.com/timothybrooks/instruct-pix2pix/assets/25627464/7c06fd49-71af-40ee-867b-8063d83d4322)

**Comment by learn01one** [comment]
same problem

**Comment by ziqipang** [comment]
@learn01one Just found a solution. Goto the huggingface space of IP2P and files, you can find and download the checkpoint there. https://huggingface.co/timbrooks/instruct-pix2pix/tree/main
