### ISSUE TITLE
How to save automatically all the images generated on a folder? In Colab

### ISSUE THREAD

**Issue by venturaEffect** [timothybrooks/instruct-pix2pix#13]
I'm using your Colab and I'm trying to figure out how to save automatically all the images generated from one prompt into a folder.

Any help?

Appreciate

**Comment by DanielFrankee** [comment]
where is the Colab?

**Comment by holynski** [comment]
Hey, we don't provide a colab, but the modification you're describing should be relatively easy to achieve by adding a for-loop into the `edit_cli.py` script.

If you'd like to play around with our app, try running `python edit_app.py` or try our model on HuggingFace (https://huggingface.co/spaces/timbrooks/instruct-pix2pix)
