### ISSUE TITLE
Idk how to run it

### ISSUE THREAD

**Issue by SamuelFrancisUMC** [timothybrooks/instruct-pix2pix#16]
How do i run it locally ? :(

The setup instructions are very sparse for a layman like be cuz i am very illiterate when it comes to coding, I have however installed SD locally and I was wondering if there is an easy way to get this to work in a WebGUI similar to that. Thanks !

**Comment by Kundanagrawalofficial** [comment]
Install all dependencies with:
```
conda env create -f environment.yaml
```

Download the pretrained models by running:
```
bash scripts/download_checkpoints.sh
```

**Comment by holynski** [comment]
If you don't want to deal with running code, another option is to try the HuggingFace demo: https://huggingface.co/spaces/timbrooks/instruct-pix2pix

Closing for now, as it's not an issue with the code. But feel free to comment more if you have questions.
