### ISSUE TITLE
Have you created a space on HuggingFace? if not can I create one?

### ISSUE THREAD

**Issue by venturaEffect** [timothybrooks/instruct-pix2pix#2]
First of all congrats on your work!

I've been looking if you created a space on HiggingFace but nothing was found.

Would you like to create one?

If not, can I create one?

Of course giving you full credit

Appreciate

**Comment by holynski** [comment]
We're working on it! Will keep you posted.

**Comment by venturaEffect** [comment]
Ok, nice!

Just wanted to make it for share to other people and give to this project more exposure :)

**Comment by holynski** [comment]
Closing for now, feel free to reopen if you don't hear back after a while.

**Comment by holynski** [comment]
Update: there's now a HuggingFace space at: https://huggingface.co/spaces/timbrooks/instruct-pix2pix
