### ISSUE TITLE
Conda problems?

### ISSUE THREAD

**Issue by theswerd** [timothybrooks/instruct-pix2pix#25]
when I run 
```bash
conda env create -f environment.yaml
```

I get 
```
Collecting package metadata (repodata.json): done
Solving environment: failed

ResolvePackageNotFound: 
  - cudatoolkit=11.3
  - numpy=1.19.2
  - python=3.8.5
  - torchvision=0.12.0
  - pytorch=1.11.0
  - pip=20.3
 ```

My device info:
MacBook Air M1 2020

**Comment by holynski** [comment]
Did some searching. Looks like a few potential reasons:

- Upgrade / downgrade your version of Conda
(https://stackoverflow.com/questions/51266535/conda-returns-solving-environment-failed)

- Add/remove conda-forge channel (or other ones you might have added). 
(https://stackoverflow.com/questions/63734508/stuck-at-solving-environment-on-anaconda)

- Change channel priority:
(https://conda.io/projects/conda/en/latest/user-guide/tasks/manage-channels.html)

I don't think this is related to our environment file, so I'm closing for now, but feel free to message more if you have questions.

**Comment by markojak** [comment]
@holynski Did you figure this out? Also on Macbook M1 and having the same issue. Updated conda etc.

**Comment by holynski** [comment]
Sorry, I won't be able to help debug this myself, as our machines are running Linux. 

In any case, I don't expect that it'll be too easy to run our code on a MacBook unless you have a dedicated Nvidia GPU.

**Comment by brycedrennan** [comment]
I generated this image in 63 seconds on my Macbook M1 😄 
> "convert to a highly detailed anime"
![005531_925892848_kdpmpp2m15_PS12 0_img2img-1_convert_to_a_highly_detailed_anime_ generated](https://user-images.githubusercontent.com/1217531/213906291-8ad35f07-bd82-4b0e-8346-c01f20811c24.jpg)

**Comment by holynski** [comment]
Well, egg on my head!

**Comment by cgreening** [comment]
@brycedrennan What was the solution to the conda problem?

**Comment by theswerd** [comment]
> I generated this image in 63 seconds on my Macbook M1 😄
> 
> > "convert to a highly detailed anime"
> > ![005531_925892848_kdpmpp2m15_PS12 0_img2img-1_convert_to_a_highly_detailed_anime_ generated](https://user-images.githubusercontent.com/1217531/213906291-8ad35f07-bd82-4b0e-8346-c01f20811c24.jpg)

could you share what commands you used for setup, and what conda channels you have active? @brycedrennan

**Comment by holynski** [comment]
> @holynski Did you figure this out? Also on Macbook M1 and having the same issue. Updated conda etc.

> @brycedrennan What was the solution to the conda problem?

1. Did you try the solutions in my above message?

> Upgrade / downgrade your version of Conda
> (https://stackoverflow.com/questions/51266535/conda-returns-solving-environment-failed)
> 
> Add/remove conda-forge channel (or other ones you might have added).
> (https://stackoverflow.com/questions/63734508/stuck-at-solving-environment-on-anaconda)
> 
> Change channel priority:
> (https://conda.io/projects/conda/en/latest/user-guide/tasks/manage-channels.html)

2. Alternatively, you can bypass Conda and instead use `pip` to install the following `requirements.txt` file:
https://huggingface.co/spaces/timbrooks/instruct-pix2pix/blob/main/requirements.txt


3. Another option is to use @brycedrennan 's repository, imaginairy:

```bash
pip install imaginairy
aimg edit image.jpg "turn him into a cyborg" 
```
