### ISSUE TITLE
'bash' is not recognized even after installing with pip command 

### ISSUE THREAD

**Issue by Kundanagrawalofficial** [timothybrooks/instruct-pix2pix#26]
'bash' is not recognized as an internal or external command,
operable program or batch file.

**Comment by holynski** [comment]
Sounds like you're probably running on Windows. Check the following issues and PRs:

#17 
#21 

Alternatively, try installing bash:
https://stackoverflow.com/questions/42438587/bash-is-not-recognized-as-an-internal-or-external-command

Closing, as I don't think it's an issue with the code, but feel free to keep messaging.
