### ISSUE TITLE
cannot import name 'StableDiffusionInstructPix2PixPipeline' from 'diffusers'

### ISSUE THREAD

**Issue by 911964** [timothybrooks/instruct-pix2pix#29]
Hi,

After cloning the repository and setting up the environment, I keep getting the following error when trying to run edit_app.py:

(ip2p) PS C:\Users\julia\instruct-pix2pix> python edit_app.py
╭─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮
│ C:\Users\julia\instruct-pix2pix\edit_app.py:9 in <module>                                        │
│                                                                                                  │
│     6 import gradio as gr                                                                        │
│     7 import torch                                                                               │
│     8 from PIL import Image, ImageOps                                                            │
│ ❱   9 from diffusers import StableDiffusionInstructPix2PixPipeline                               │
│    10                                                                                            │
│    11                                                                                            │
│    12 help_text = """                                                                            │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
ImportError: cannot import name 'StableDiffusionInstructPix2PixPipeline' from 'diffusers'
(C:\Users\julia\.conda\envs\ip2p\lib\site-packages\diffusers\__init__.py)

Do you have a suggestion for how I could fix this? Thank you very much in advance

**Comment by Kundanagrawalofficial** [comment]
This error message is indicating that there is a problem with an import statement in your code, specifically in the file diffusers_init_.py. The error message states that the import is trying to import the module StableDiffusionInstructPix2PixPipeline from the package diffusers, but it is unable to find it.

Possible causes for this error include:

The module or package being imported does not exist in the specified location.
The package or module has been renamed or moved to a different location.
There is a typo in the import statement.
You should check the spelling and capitalization of the package and module names in your import statement, and ensure that they exist in the specified location. You may also need to update your import statement if the package or module has been moved or renamed.

**Comment by patrickvonplaten** [comment]
Hey @911964,

Could you upgrade `diffusers` to current main?:

```
pip install git+https://github.com/huggingface/diffusers.git
```

and then:

```py
from diffusers import StableDiffusionInstructPix2PixPipeline
```

should work

**Comment by holynski** [comment]
Looks like this is an issue setting up the code from the HuggingFace space. Above comment should resolve the issue, so I'm closing for now, but feel free to keep commenting.
