### ISSUE TITLE
How to make Windows 10 recognize Bash

### ISSUE THREAD

**Issue by webdevserv** [timothybrooks/instruct-pix2pix#37]
Windows 10 (check if bash or wsl not working)
if not working:

if you run wsl --install and see the WSL help text, please try running wsl --list --online to see a list of available distros and run wsl --install -d <DistroName> to install a distro. To uninstall WSL, see Uninstall legacy version of WSL or unregister or uninstall a Linux distribution.

after installation test

try 
wsl bash -c "echo hi from simple script"

the echo should work.

**Comment by holynski** [comment]
Looks like this is a solution to a problem.
