### ISSUE TITLE
RuntimeError: CUDA out of memory

### ISSUE THREAD

**Issue by ldyeax** [timothybrooks/instruct-pix2pix#38]
`RuntimeError: CUDA out of memory. Tried to allocate 58.00 MiB (GPU 0; 11.00 GiB total capacity; 10.04 GiB already allocated; 0 bytes free; 10.21 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF`

I've tried closing everything else that uses any GPU memory, but it always says "0 bytes free". 

Trying to use edit_app.py in PowerShell on Windows 10
conda 22.11.1
2080Ti 11GB

**Comment by holynski** [comment]
Hey, we recently updated the README to clarify that the default configuration needs >18GB of GPU memory, so your device probably doesn't have enough memory.

There are, however, a few other ways of running our model with less memory, listed at the bottom of the page [here](https://github.com/timothybrooks/instruct-pix2pix#other-ways-of-using-instructpix2pix).
