### ISSUE TITLE
huggingface instruct-pix2pix fails 

### ISSUE THREAD

**Issue by webdevserv** [timothybrooks/instruct-pix2pix#39]
In hugging face.
timbrooks/instruct-pix2pix

Trying to turn David into a cyborg with the same 
settings as your readme does not work.
It returns a multi color blur.

Fix CFG ON

Text CFG        Image CFG
7.5                 1.2

**Comment by holynski** [comment]
I used the HuggingFace space just now, and it seemed to work fine.

<img width="1062" alt="Screenshot 2023-01-23 at 11 16 26 AM" src="https://user-images.githubusercontent.com/18318354/214129570-e7d4d289-5eee-48bc-ae52-dcd182489d98.png">
