### ISSUE TITLE
[Tutorial] Forget Photoshop - How To Transform Images With Text Prompts using InstructPix2Pix Model in NMKD GUI

### ISSUE THREAD

**Issue by FurkanGozukara** [timothybrooks/instruct-pix2pix#47]
This is not an issue.

I hope you can add this tutorial to the readme section of the page

Thank you so much for this new great AI model. I hope you even release its improved version soon

My tutorial could be the first one to use it with easiest way

https://youtu.be/EPRa8EZl9Os

[![image](https://user-images.githubusercontent.com/19240467/214596092-052ea5b9-3894-4075-bddb-7ac0421732b9.png)](https://youtu.be/EPRa8EZl9Os)

**Comment by holynski** [comment]
Feel free to submit a pull request for this! Closing issue for now.
