### ISSUE TITLE
Model Drive Link

### ISSUE THREAD

**Issue by lazy-nurd** [timothybrooks/instruct-pix2pix#5]
Hello,
Thank you so much for the amazing work. Model downloading is very slow even in the presence of high quality network. I have tried on both colab and local and both are requiring to download for more than 2 hours.
![Screenshot from 2023-01-19 21-35-37](https://user-images.githubusercontent.com/110412845/213500081-8d7b71ca-2dc7-49b6-960f-7f9efba91872.png)
Can you please google drive link ?
Thanks

**Comment by holynski** [comment]
Google Drive will likely be just as inconvenient, unfortunately, if not more. For large files, Drive will disable downloading if a file has had too much traffic over the last 24 hours. 

We're looking into other places to host the model, but we ask that you be patient with our overloaded servers for the time being.
