### ISSUE TITLE
Negative prompts

### ISSUE THREAD

**Issue by Rizvanov-Rinat** [timothybrooks/instruct-pix2pix#54]
Hi, is it possible to use negative prompts?

**Comment by G-force78** [comment]
Yes just add --negative-prompt 
eg: `!aimg edit {enter image path here without brackets eg content/images/initimagename} "prompt goes here" --negative-prompt "negative prompt goes here" --prompt-strength 10 --steps 50`

**Comment by Rizvanov-Rinat** [comment]
> 

Thank you! And maybe you know how to add negative prompt in edit_cli.py?

**Comment by G-force78** [comment]
> > 
> 
> Thank you! And maybe you know how to add negative prompt in edit_cli.py?

No sorry and that above was for imaginairy they are slightly different
