### ISSUE TITLE
can you make it run in free colab?

### ISSUE THREAD

**Issue by loboere** [timothybrooks/instruct-pix2pix#6]
please create a free level colab to run this

**Comment by holynski** [comment]
Working on it!

**Comment by fa16-030** [comment]
Hi @holynski , 
on free colab, its giving RAM OOM after running thus:
`!python3 edit_cli.py \
    --steps 100 \
    --resolution 512 \
    --seed 1371 \
    --cfg-text 7.5 \
    --cfg-image 1.2 \
    --input imgs/example.jpg \
    --output imgs/output.jpg \
    --edit "turn him into a cyborg"`

**Comment by ForceConstant** [comment]
@holynski did you close this because there is a working colab free notebook?

**Comment by Gero39** [comment]
> @holynski did you close this because there is a working colab free notebook?

What notebook?
