### ISSUE TITLE
public training logs

### ISSUE THREAD

**Issue by tals** [timothybrooks/instruct-pix2pix#62]
Hey there, and thanks for this cool piece of work!
Would it be possible to make the the wandb training logs public?

It would be super helpful for building on top of this work.

**Comment by holynski** [comment]
Hey, thanks!

Unfortunately the model checkpoints we released weren't trained with wandb logging.

**Comment by tals** [comment]
Could you release any training logs, in any format, even for other successful runs?

**Comment by tals** [comment]
Do you have any training logs you could release, in any format, even for other successful runs?

I am mostly looking to get some signals for the expected behavior of my own runs :)
