### ISSUE TITLE
Error in Finetuning using released checkpoint

### ISSUE THREAD

**Issue by alphacoder01** [timothybrooks/instruct-pix2pix#74]
Hello, I plan to finetune the instruct-pix2pix model from the released checkpoint to another dataset.

I'm using the following command 
`CUDA_VISIBLE_DEVICES=0,1,2,3 python main.py --name finetune_test --base configs/train.yaml --train --gpus 0,1,2,3 --resume --logdir ~/scratch/Experiments/ip2p/`

I've already placed the `instruct-pix2pix-00-22000.ckpt` in the corresponding `logdir/checkpoints` renaming it as `last.ckpt` and put the required config files as well.

but the following error comes up when I the main.py loads the model.
`KeyError: 'epoch_loop.batch_loop.optim_progress`
I'm not sure how to handle this.

**I'm able to train from scratch on my dataset**, but I wanted to see if finetuning would give better results.

Appreciate any help.
Regards!

**Comment by styfeng** [comment]
@alphacoder01 how did you get training working from scratch on your own dataset? i am trying to use four 24gb vram GPUs (96gb total vram) and get cuda OOM memory even on batch size 1 for 256x256 resolution images. it seems impossible to train. i wonder if it's a bug from my end or not.

**Comment by tekakutli** [comment]
@styfeng  and here I was trying to get it to finetune having 16gb

it's over

**Comment by alphacoder01** [comment]
> @alphacoder01 how did you get training working from scratch on your own dataset? i am trying to use four 24gb vram GPUs (96gb total vram) and get cuda OOM memory even on batch size 1 for 256x256 resolution images. It seems impossible to train. i wonder if it's a bug from my end or not.

I trained using 4 Nvidia-A100 (80 GB). Each GPUs memory consumption was around 60/65 % with default batch size and gradient accumulation steps. @styfeng  I think it's more to do with the memory the model consumes than the batch size.

**Comment by styfeng** [comment]
@alphacoder01 yeah i just tried using an A40 (40GB of VRAM) and it trains fine with batch size up to 64. it seems that you're correct, the model by default consumes around 26gb of VRAM or more (I believe), so distributing across 24GB GPUs doesn't work.

@tekakutli yeah... maybe try to see if you can get one GPU with at least 30gb of VRAM somehow lol

**Comment by alphacoder01** [comment]
> Hello, I plan to finetune the instruct-pix2pix model from the released checkpoint to another dataset.
> 
> I'm using the following command `CUDA_VISIBLE_DEVICES=0,1,2,3 python main.py --name finetune_test --base configs/train.yaml --train --gpus 0,1,2,3 --resume --logdir ~/scratch/Experiments/ip2p/`
> 
> I've already placed the `instruct-pix2pix-00-22000.ckpt` in the corresponding `logdir/checkpoints` renaming it as `last.ckpt` and put the required config files as well.
> 
> but the following error comes up when I the main.py loads the model. `KeyError: 'epoch_loop.batch_loop.optim_progress` I'm not sure how to handle this.
> 
> **I'm able to train from scratch on my dataset**, but I wanted to see if finetuning would give better results.
> 
> Appreciate any help. Regards!

As a temporary fix, I was able to fine-tune from the released checkpoint using the following changes:
1. I made a change [here](https://github.com/timothybrooks/instruct-pix2pix/blob/main/stable_diffusion/ldm/models/diffusion/ddpm_edit.py#L496)
from 
`self.init_from_ckpt(ckpt_path, ignore_keys)`
To
`self.init_from_ckpt(ckpt_path, ignore_keys, only_model=True)` 

2. added `resume_from_checkpoint: logdir/checkpoints/last.ckpt` in lightining.yaml file in configs

**Comment by styfeng** [comment]
@alphacoder01 thanks that's useful! which exact `lightning.yaml` file are you referring to? do you mean `train.yaml`?
also actually I think I've gotten fine-tuning on the released checkpoint working by just pointing `ckpt_path` in `train.yaml` to the pretrained checkpoint, e.g. `checkpoints/instruct-pix2pix-00-22000.ckpt`

**Comment by alphacoder01** [comment]
@styfeng, during training in the logdir, a directory named `configs` is create. Under that, we have 2 .yaml files (lightining.yaml and project.yaml). That's what I'm referring to. I copied those files from another run (training from scratch) and made changes to them

**Comment by alphacoder01** [comment]
> @alphacoder01 thanks that's useful! which exact `lightning.yaml` file are you referring to? do you mean `train.yaml`? also actually I think I've gotten fine-tuning on the released checkpoint working by just pointing `ckpt_path` in `train.yaml` to the pretrained checkpoint, e.g. `checkpoints/instruct-pix2pix-00-22000.ckpt`

lol, I'll have to try it then

**Comment by alphacoder01** [comment]
@styfeng I used your suggestion to finetune by just replacing the `ckpt_path`,  but Using that starts the training from epoch 0, whereas the method I suggested resumes the training from ~22,000th step. Don't know whether it makes a difference, will have to test them.

**Comment by finninmunich** [comment]
> @styfeng I used your suggestion to finetune by just replacing the `ckpt_path`, but Using that starts the training from epoch 0, whereas the method I suggested resumes the training from ~22,000th step. Don't know whether it makes a difference, will have to test them.

Hi, have you got any results? :)

**Comment by victorzarzu** [comment]
> @alphacoder01 thanks that's useful! which exact `lightning.yaml` file are you referring to? do you mean `train.yaml`? also actually I think I've gotten fine-tuning on the released checkpoint working by just pointing `ckpt_path` in `train.yaml` to the pretrained checkpoint, e.g. `checkpoints/instruct-pix2pix-00-22000.ckpt`

Hi! I followed these steps, but I still receive the problem that you stated. Did you do something else specifically? Thank you!
