### ISSUE TITLE
instantiate_from_config and segmentation fault (core dumped)

### ISSUE THREAD

**Issue by YIFanH** [timothybrooks/instruct-pix2pix#83]
Hi Dear authors

thanks for your work, I use clip_test.py for edit image,but instantiate_from_config function is segmentation fault which line is return getattr(importlib.import_module(module, package=None), cls) in ./stable_diffusion/ldm/util.py，i don‘t known why and have you ever encountered this kind of problem？

thanks for your reply and best wishes !

**Comment by Helenalov12** [comment]
![Screenshot_20230227-011712](https://user-images.githubusercontent.com/123447809/221542223-c271a9b9-34a0-4205-87fb-a4b6b4337132.png)
Q
