### ISSUE TITLE
Hello from ControlNet

### ISSUE THREAD

**Issue by lllyasviel** [timothybrooks/instruct-pix2pix#89]
Hello instruct-pix2pix,

This is team of ControlNet. We trained a controlnet model with ip2p dataset [here](https://github.com/lllyasviel/ControlNet-v1-1-nightly). See the section "ControlNet 1.1 Instruct Pix2Pix".

Rightnow the behavior of that model is different but the performance is similar to official ip2p. Do you think it is possible to improve the robustness with better datasets or some other stratagies?

**Comment by PospoSK** [comment]
Is there any tutorial, how it works now in A1111? Thx.

**Comment by andreemic** [comment]
Do you have any more specific observations of the performance compared to the original InstructPix2Pix?

We've fine-tuned both ControlNet and ip2p on a 50k hand-filtered task-specific dataset and might have some insights. @lllyasviel

**Comment by peterwilli** [comment]
I trained my own [controlnet instructpix2pix](https://huggingface.co/peterwilli/control_instruct_pix2pix_beta_1) a few weeks prior. Idk if it helps, but here is a demo: https://colab.research.google.com/drive/1kG7rLHGC4rGrLwGIGKiNsFZI7vh-_fB4?usp=sharing

It's trained on the full clip-filtered dataset.

**Comment by timothybrooks** [comment]
Hi @lllyasviel, awesome work on ControlNet :) I believe there is plenty of room to improve the robustness of instruct-pix2pix, in particular by improving the training dataset (generating better captions/edit instructions, better models/methods for generating pairs of images, and better dataset filtering). There are probably other strategies to improve it as well.

**Comment by massyzs** [comment]
It seems that controlnet version Ip2p can only recognize the instruction while losing some special features. Ip2p surprisingly is good at 3D tasks while SD+controlnet_ip2p cannot guarantee 3D consistency.
