### ISSUE TITLE
cost for finetuning GPT-3

### ISSUE THREAD

**Issue by joellliu** [timothybrooks/instruct-pix2pix#90]
Hi, thanks for the great work. Can you share how much it costs for fine-tuning GPT-3 on your manually written instruction datasets? Thanks!

**Comment by timothybrooks** [comment]
Fine-tuning cost ~$10, and generating the entire text dataset with the fine-tuned model cost ~$4k. This was back in pre-ChatGPT and pre-GPT4 days, and the API prices change over time.
